version: '3.8'

services:
  user-service:
    build:
      context: ./services/user-service
    ports:
      - "5001:5000"
    env_file:
      - ./services/user-service/.env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/vortexcommerce-users

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  product-service:
    build:
      context: ./services/product-service
    ports:
      - "5002:5000"
    env_file:
      - ./services/product-service/.env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/vortexcommerce-products

  shopping-cart-service:
    build:
      context: ./services/shopping-cart-service
    ports:
      - "5003:5000"
    env_file:
      - ./services/shopping-cart-service/.env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/vortexcommerce-cart

  order-service:
    build:
      context: ./services/order-service
    ports:
      - "5004:5000"
    env_file:
      - ./services/order-service/.env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/vortexcommerce-orders

volumes:
  mongo-data:
