version: '3'
services:
  user-service:
    build:
      context: ./services/user-service
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"